### ISSUE TITLE
Another SDL 2 project

### ISSUE THREAD

**Issue by saward** [adam000/Go-SDL2#2]
Hi,

Just wondering if you have tried this:
https://github.com/DeedleFake/sdl

I have not tried yours, or theirs, so I cannot compare.

**Comment by saward** [comment]
Also:
- https://github.com/jackyb/go-sdl2
- https://github.com/velour/ui
- https://github.com/scottferg/Go-SDL2

I have no idea what stage any of these projects are at.

**Comment by adam000** [comment]
I haven't tried these, thanks for pointing them out. Right now my project's only capable of drawing windows and basically running this example: https://github.com/adam000/go-sdl-gl-examples/tree/master/drawWithSdlHelloWorld But I plan on making it better (or perhaps adding to one of these already-existing projects, if they're worth it)

**Comment by adam000** [comment]
jackyb/go-sdl2 and scottferg/Go-SDL2 look promising, however I'm looking to also get more experience in Go (I have a friend who's been coding since the Go beta and he's helping me with code review and such), so I'm gonna implement it myself.

Thanks for pointing these out though! It's nice to see that the community's active :)

**Comment by saward** [comment]
Learning experience is a good enough reason!
